version = 5.4.0
archive_dir = /etc/letsencrypt/archive/mm.tsyndra.ru
cert = /etc/letsencrypt/live/mm.tsyndra.ru/cert.pem
privkey = /etc/letsencrypt/live/mm.tsyndra.ru/privkey.pem
chain = /etc/letsencrypt/live/mm.tsyndra.ru/chain.pem
fullchain = /etc/letsencrypt/live/mm.tsyndra.ru/fullchain.pem
[renewalparams]
account = ec2b0a28ec2d96006f85fff459f592a9
pref_challs = http-01,
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
mm.tsyndra.ru = /var/www/certbot
