# HTTP: Let's Encrypt challenge + редирект на Mattermost (HTTPS на нестандартном порту)
server {
    listen 80;
    listen [::]:80;
    server_name mm.tsyndra.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host:30445$request_uri;
    }
}
